document_analysis:
  description: "1500 insurance claim form config file"
  document_type: "1500"
  api_version: "2023-07-31"
  model: "prebuilt-read"

fields:
  - name: "total_charges"
    cardinality: 1
    cropping:
      label: "totacharges"
      x_offset: 0
      y_offset: 0      
      side_border: 1
      height_multiplier: 4.5
      width_multiplier: 1.3      
      detection_threshold: 0.20
      max_height: 400
      max_width: 400
    postprocessing:
      module: "1500.total_charges"
  - name: "charges"
    cardinality: 6
    cropping:
      label: "charges"
      x_offset: 0
      y_offset: 0      
      side_border: 7
      height_multiplier: 10
      width_multiplier: 1
      detection_threshold: 0.7
      max_height: 400
      max_width: 400
    postprocessing:
      module: "1500.charges"
  - name: "qty"
    cardinality: 6
    cropping:
      label: "qty"
      x_offset: 0
      y_offset: 0
      side_border: 7
      height_multiplier: 10
      width_multiplier: 1
      detection_threshold: 0.55
      max_height: 390
      max_width: 400
    postprocessing:
      module: "1500.qty"     
  - name: "start_date"
    cardinality: 6
    cropping:
      label: "datesofservice"
      x_offset: 0
      y_offset: 0      
      side_border: 7
      height_multiplier: 10
      width_multiplier: 1
      detection_threshold: 0.7
      max_height: 390
      max_width: 172
    postprocessing:
      module: "1500.datesofservice"
  - name: "end_date"
    cardinality: 6
    cropping:
      label: "datesofservice"
      x_offset: 170
      y_offset: 0         
      side_border: 7
      height_multiplier: 10
      width_multiplier: 1
      detection_threshold: 0.7
      max_height: 390
      max_width: 400
    postprocessing:
      module: "1500.datesofservice"
  - name: "birth_date"
    cardinality: 1
    cropping:
      label: "birthdate"
      x_offset: 0
      y_offset: 3      
      side_border: 5
      height_multiplier: 1.5
      width_multiplier: 1.1
      detection_threshold: 0.4
      max_height: 400
      max_width: 400
    postprocessing:
      module: "1500.birth_date"